### ISSUE TITLE
有一个花里胡哨的建议，绝对美观

### ISSUE THREAD

**Issue by oeieo** [fishjar/kiss-translator#16]
### 1. 这里的文字样式，选择高亮，生成到页面，为啥不是[background: ] 而是[background-color: ]，可以改为background吗？
![image](https://github.com/fishjar/kiss-translator/assets/112836653/d580c334-a6ca-4d5a-8225-2037d60f8754)
### 2. background 可以设置花里胡哨的颜色比如
![image](https://github.com/fishjar/kiss-translator/assets/112836653/6eb2a13c-f269-4ce1-affe-90ce7949d773)

**Comment by oeieo** [comment]
background: linear-gradient(45deg, #C7F5FE 10%, #C7F5FE 40%, #FCC8F8 40%, #FCC8F8 60%, #EAB4F8 60%, #EAB4F8 65%, #F3F798 65%, #F3F798 90%) !important

**Comment by fishjar** [comment]
1、你这个建议很“漂亮”，或许可以进一步支持自定义样式
2、关于为什么是`background-color`，因为为了减少设置的输入，这个高亮的背景色和线条的颜色共用了字段，所以你看到设置那里显示的是`样式颜色`，而不是`高亮背景色`

**Comment by fishjar** [comment]
花里胡哨的写法已经安排，[v1.6.1](https://github.com/fishjar/kiss-translator/releases/tag/v1.6.1) 支持自定义样式了。

**Comment by leic4u** [comment]
这个需求很牛逼，不是搞过前端开发的一般还想不到这个点子，但有了真的很棒。但是对于普通人来说，想自己搞有点难，看能不能默认提供一些“花里胡哨”的自定义样式？

迫不及待想体验了，chrome 商店和 greasyfork 商店都还没更新，只能装一个作者博客安装地址的版本了🤣

**Comment by fishjar** [comment]
> 这个需求很牛逼，不是搞过前端开发的一般还想不到这个点子，但有了真的很棒。但是对于普通人来说，想自己搞有点难，看能不能默认提供一些“花里胡哨”的自定义样式？
> 
> 迫不及待想体验了，chrome 商店和 greasyfork 商店都还没更新，只能装一个作者博客安装地址的版本了🤣

给个样式：

```css
color: #666;
background: linear-gradient(
  45deg,
  LightGreen 20%,
  LightPink 20% 40%,
  LightSalmon 40% 60%,
  LightSeaGreen 60% 80%,
  LightSkyBlue 80%
);
&:hover {
  color: #333;
};
```
![Screenshot from 2023-09-02 00-00-50](https://github.com/fishjar/kiss-translator/assets/1157624/aebe0bfc-8e7b-457a-803b-06b198ec6051)
